import { NextResponse } from 'next/server';
import pool from '@/lib/db';

export async function GET() {
  const connection = await pool.getConnection();
  try {
    const queries = [
      `INSERT INTO rrhh_trabajadores (         rut, nombres, apellido_paterno, apellido_materno, nacionalidad, fecha_nacimiento,          direccion, telefono, email, nivel_educacional, estado_civil,          afp_id, salud_id, cargas_familiares, banco, tipo_cuenta, numero_cuenta, entrega_riohs, es_representante_legal       ) VALUES (         '13421122-9', 'Dayan', 'Barrera', 'Cortés',          'CHILENA', '1978-09-13',          'Subida del Desierto 317', '+56 993258016', 'dayanbarrera@gmail.com',          'SUPERIOR', 'DIVORCIADA',          (SELECT id FROM rrhh_afp WHERE nombre LIKE '%CUPR%' LIMIT 1),          (SELECT id FROM rrhh_salud WHERE nombre LIKE '%CRUZ%' LIMIT 1),          0, 'ITAU', 'CORRIENTE', '21382887',          0, 1       )       ON DUPLICATE KEY UPDATE          nombres=VALUES(nombres), apellido_paterno=VALUES(apellido_paterno), apellido_materno=VALUES(apellido_materno),         banco=VALUES(banco), tipo_cuenta=VALUES(tipo_cuenta), numero_cuenta=VALUES(numero_cuenta),         nacionalidad=VALUES(nacionalidad), nivel_educacional=VALUES(nivel_educacional);`,
      `INSERT INTO rrhh_trabajadores (         rut, nombres, apellido_paterno, apellido_materno, nacionalidad, fecha_nacimiento,          direccion, telefono, email, nivel_educacional, estado_civil,          afp_id, salud_id, cargas_familiares, banco, tipo_cuenta, numero_cuenta, entrega_riohs, es_representante_legal       ) VALUES (         '15925633-2', 'Yennifer', 'Román ', 'Díaz',          'CHILENA', '1984-12-29',          'Carlos Pérez Bretti 9742', '+56 994110836', 'yennyroman_22@hotmail.com',          'MEDIA', 'SOLTERA',          (SELECT id FROM rrhh_afp WHERE nombre LIKE '%CUPR%' LIMIT 1),          (SELECT id FROM rrhh_salud WHERE nombre LIKE '%FONA%' LIMIT 1),          0, 'ESTADO', 'CORRIENTE', '2500334200',          1, 1       )       ON DUPLICATE KEY UPDATE          nombres=VALUES(nombres), apellido_paterno=VALUES(apellido_paterno), apellido_materno=VALUES(apellido_materno),         banco=VALUES(banco), tipo_cuenta=VALUES(tipo_cuenta), numero_cuenta=VALUES(numero_cuenta),         nacionalidad=VALUES(nacionalidad), nivel_educacional=VALUES(nivel_educacional);`,
      `INSERT INTO rrhh_trabajadores (         rut, nombres, apellido_paterno, apellido_materno, nacionalidad, fecha_nacimiento,          direccion, telefono, email, nivel_educacional, estado_civil,          afp_id, salud_id, cargas_familiares, banco, tipo_cuenta, numero_cuenta, entrega_riohs, es_representante_legal       ) VALUES (         '25022361-7', 'Ludivia', 'Chiquito', 'Osorio',          'COLOMBIANA', '1968-11-05',          'Esmeralda 2045', '+56 948597665', 'josefa113@gmail.com',          'MEDIA', 'DIVORCIADA',          (SELECT id FROM rrhh_afp WHERE nombre LIKE '%ING %' LIMIT 1),          (SELECT id FROM rrhh_salud WHERE nombre LIKE '%FONA%' LIMIT 1),          0, 'ESTADO', 'VISTA', '25022361',          1, 1       )       ON DUPLICATE KEY UPDATE          nombres=VALUES(nombres), apellido_paterno=VALUES(apellido_paterno), apellido_materno=VALUES(apellido_materno),         banco=VALUES(banco), tipo_cuenta=VALUES(tipo_cuenta), numero_cuenta=VALUES(numero_cuenta),         nacionalidad=VALUES(nacionalidad), nivel_educacional=VALUES(nivel_educacional);`,
      `INSERT IGNORE INTO rrhh_cargos (nombre) VALUES ('Auxiliar de aseo');`,
      `INSERT INTO rrhh_contratos (trabajador_id, cargo_id, sueldo_base, fecha_inicio, tipo_contrato, estado)         SELECT t.id, c.id, 390000, '2018-03-31', 'Indefinido', 'ACTIVO'         FROM rrhh_trabajadores t, rrhh_cargos c         WHERE t.rut = '25022361-7' AND c.nombre = 'Auxiliar de aseo'         ON DUPLICATE KEY UPDATE sueldo_base=390000, cargo_id=VALUES(cargo_id);`,
      `INSERT INTO rrhh_haberes_fijos (trabajador_id, colacion, movilizacion)         SELECT id, 15000, 15000 FROM rrhh_trabajadores WHERE rut = '25022361-7'         ON DUPLICATE KEY UPDATE colacion=15000, movilizacion=15000;`,
      `INSERT INTO rrhh_trabajadores (         rut, nombres, apellido_paterno, apellido_materno, nacionalidad, fecha_nacimiento,          direccion, telefono, email, nivel_educacional, estado_civil,          afp_id, salud_id, cargas_familiares, banco, tipo_cuenta, numero_cuenta, entrega_riohs, es_representante_legal       ) VALUES (         '8346245-', 'Juan Luis', 'Salamanca ', 'Lecaros',          'CHILENA', '1966-09-11',          'Subida del Desierto 317', '+56 966190114', 'juanluis.salamanca@gmail.com',          'SUPERIOR', 'DIVORCIADO',          (SELECT id FROM rrhh_afp WHERE nombre LIKE '%CUPR%' LIMIT 1),          (SELECT id FROM rrhh_salud WHERE nombre LIKE '%CRUZ%' LIMIT 1),          0, 'SANTANDER', 'CORRIENTE', '62173289',          0, 0       )       ON DUPLICATE KEY UPDATE          nombres=VALUES(nombres), apellido_paterno=VALUES(apellido_paterno), apellido_materno=VALUES(apellido_materno),         banco=VALUES(banco), tipo_cuenta=VALUES(tipo_cuenta), numero_cuenta=VALUES(numero_cuenta),         nacionalidad=VALUES(nacionalidad), nivel_educacional=VALUES(nivel_educacional);`,
      `INSERT INTO rrhh_trabajadores (         rut, nombres, apellido_paterno, apellido_materno, nacionalidad, fecha_nacimiento,          direccion, telefono, email, nivel_educacional, estado_civil,          afp_id, salud_id, cargas_familiares, banco, tipo_cuenta, numero_cuenta, entrega_riohs, es_representante_legal       ) VALUES (         '15024777-2', 'Paulina', 'Castro', 'Martinez',          'CHILENA', '1983-06-10',          'Av. Oscar Bonilla 8617', '+56 973027220', 'pauly.castro.m@gmail.com',          'MEDIA', 'CASADA',          (SELECT id FROM rrhh_afp WHERE nombre LIKE '%ING %' LIMIT 1),          (SELECT id FROM rrhh_salud WHERE nombre LIKE '%FONA%' LIMIT 1),          0, 'FALABELLA', 'VISTA', '50250033956',          0, 0       )       ON DUPLICATE KEY UPDATE          nombres=VALUES(nombres), apellido_paterno=VALUES(apellido_paterno), apellido_materno=VALUES(apellido_materno),         banco=VALUES(banco), tipo_cuenta=VALUES(tipo_cuenta), numero_cuenta=VALUES(numero_cuenta),         nacionalidad=VALUES(nacionalidad), nivel_educacional=VALUES(nivel_educacional);`,
      `INSERT IGNORE INTO rrhh_cargos (nombre) VALUES ('Administrativa');`,
      `INSERT INTO rrhh_contratos (trabajador_id, cargo_id, sueldo_base, fecha_inicio, tipo_contrato, estado)         SELECT t.id, c.id, 740000, '2020-10-31', 'Indefinido', 'ACTIVO'         FROM rrhh_trabajadores t, rrhh_cargos c         WHERE t.rut = '15024777-2' AND c.nombre = 'Administrativa'         ON DUPLICATE KEY UPDATE sueldo_base=740000, cargo_id=VALUES(cargo_id);`,
      `INSERT INTO rrhh_haberes_fijos (trabajador_id, colacion, movilizacion)         SELECT id, 20000, 20000 FROM rrhh_trabajadores WHERE rut = '15024777-2'         ON DUPLICATE KEY UPDATE colacion=20000, movilizacion=20000;`,
      `INSERT INTO rrhh_trabajadores (         rut, nombres, apellido_paterno, apellido_materno, nacionalidad, fecha_nacimiento,          direccion, telefono, email, nivel_educacional, estado_civil,          afp_id, salud_id, cargas_familiares, banco, tipo_cuenta, numero_cuenta, entrega_riohs, es_representante_legal       ) VALUES (         '13181825-4', 'Verónica', 'Moreno', 'Cortés',          'CHILENA', '1977-04-25',          'Juan Ferra 8195', '+56 958636314', 'veronica.moreno.c77@gmail.com',          'TECNICO', 'SOLTERA',          (SELECT id FROM rrhh_afp WHERE nombre LIKE '%CUPR%' LIMIT 1),          (SELECT id FROM rrhh_salud WHERE nombre LIKE '%FONA%' LIMIT 1),          0, 'BCI', 'CORRIENTE', '30213118',          0, 1       )       ON DUPLICATE KEY UPDATE          nombres=VALUES(nombres), apellido_paterno=VALUES(apellido_paterno), apellido_materno=VALUES(apellido_materno),         banco=VALUES(banco), tipo_cuenta=VALUES(tipo_cuenta), numero_cuenta=VALUES(numero_cuenta),         nacionalidad=VALUES(nacionalidad), nivel_educacional=VALUES(nivel_educacional);`,
      `INSERT IGNORE INTO rrhh_cargos (nombre) VALUES ('Administrativa');`,
      `INSERT INTO rrhh_contratos (trabajador_id, cargo_id, sueldo_base, fecha_inicio, tipo_contrato, estado)         SELECT t.id, c.id, 900000, '2021-12-31', 'Indefinido', 'ACTIVO'         FROM rrhh_trabajadores t, rrhh_cargos c         WHERE t.rut = '13181825-4' AND c.nombre = 'Administrativa'         ON DUPLICATE KEY UPDATE sueldo_base=900000, cargo_id=VALUES(cargo_id);`,
      `INSERT INTO rrhh_haberes_fijos (trabajador_id, colacion, movilizacion)         SELECT id, 62500, 62500 FROM rrhh_trabajadores WHERE rut = '13181825-4'         ON DUPLICATE KEY UPDATE colacion=62500, movilizacion=62500;`,
      `INSERT INTO rrhh_trabajadores (         rut, nombres, apellido_paterno, apellido_materno, nacionalidad, fecha_nacimiento,          direccion, telefono, email, nivel_educacional, estado_civil,          afp_id, salud_id, cargas_familiares, banco, tipo_cuenta, numero_cuenta, entrega_riohs, es_representante_legal       ) VALUES (         '18687706-3', 'Tamara', 'Alfaro', 'Miranda',          'CHILENA', '1993-10-08',          'Pasaje El Toldo 1369', '+56 992982299', 't.alfaromiranda9@hotmail.com',          'MEDIA', 'SOLTERA',          (SELECT id FROM rrhh_afp WHERE nombre LIKE '%ING %' LIMIT 1),          (SELECT id FROM rrhh_salud WHERE nombre LIKE '%FONA%' LIMIT 1),          0, 'BCI', 'VISTA', '43620922',          0, 1       )       ON DUPLICATE KEY UPDATE          nombres=VALUES(nombres), apellido_paterno=VALUES(apellido_paterno), apellido_materno=VALUES(apellido_materno),         banco=VALUES(banco), tipo_cuenta=VALUES(tipo_cuenta), numero_cuenta=VALUES(numero_cuenta),         nacionalidad=VALUES(nacionalidad), nivel_educacional=VALUES(nivel_educacional);`,
      `INSERT IGNORE INTO rrhh_cargos (nombre) VALUES ('Auxiliar Farmacéutico ');`,
      `INSERT INTO rrhh_contratos (trabajador_id, cargo_id, sueldo_base, fecha_inicio, tipo_contrato, estado)         SELECT t.id, c.id, 420000, '2022-02-04', 'Indefinido', 'ACTIVO'         FROM rrhh_trabajadores t, rrhh_cargos c         WHERE t.rut = '18687706-3' AND c.nombre = 'Auxiliar Farmacéutico '         ON DUPLICATE KEY UPDATE sueldo_base=420000, cargo_id=VALUES(cargo_id);`,
      `INSERT INTO rrhh_haberes_fijos (trabajador_id, colacion, movilizacion)         SELECT id, 37500, 37500 FROM rrhh_trabajadores WHERE rut = '18687706-3'         ON DUPLICATE KEY UPDATE colacion=37500, movilizacion=37500;`,
      `INSERT INTO rrhh_trabajadores (         rut, nombres, apellido_paterno, apellido_materno, nacionalidad, fecha_nacimiento,          direccion, telefono, email, nivel_educacional, estado_civil,          afp_id, salud_id, cargas_familiares, banco, tipo_cuenta, numero_cuenta, entrega_riohs, es_representante_legal       ) VALUES (         '10011860-2', 'Elina', 'Fernández', 'Galleguillos',          'CHILENA', '1966-01-07',          'Benito Ocampo 10825. Depto C 13', '+56 976220375', 'eliafernandezgalleguillos@gmail.com',          'MEDIA', 'SOLTERA',          (SELECT id FROM rrhh_afp WHERE nombre LIKE '%PROV%' LIMIT 1),          (SELECT id FROM rrhh_salud WHERE nombre LIKE '%FONA%' LIMIT 1),          0, 'FALABELLA', 'CORRIENTE', '1-151-007673-0',          0, 1       )       ON DUPLICATE KEY UPDATE          nombres=VALUES(nombres), apellido_paterno=VALUES(apellido_paterno), apellido_materno=VALUES(apellido_materno),         banco=VALUES(banco), tipo_cuenta=VALUES(tipo_cuenta), numero_cuenta=VALUES(numero_cuenta),         nacionalidad=VALUES(nacionalidad), nivel_educacional=VALUES(nivel_educacional);`,
      `INSERT IGNORE INTO rrhh_cargos (nombre) VALUES ('Auxiliar Farmacéutico ');`,
      `INSERT INTO rrhh_contratos (trabajador_id, cargo_id, sueldo_base, fecha_inicio, tipo_contrato, estado)         SELECT t.id, c.id, 740000, '2022-04-30', 'Indefinido', 'ACTIVO'         FROM rrhh_trabajadores t, rrhh_cargos c         WHERE t.rut = '10011860-2' AND c.nombre = 'Auxiliar Farmacéutico '         ON DUPLICATE KEY UPDATE sueldo_base=740000, cargo_id=VALUES(cargo_id);`,
      `INSERT INTO rrhh_haberes_fijos (trabajador_id, colacion, movilizacion)         SELECT id, 17500, 17500 FROM rrhh_trabajadores WHERE rut = '10011860-2'         ON DUPLICATE KEY UPDATE colacion=17500, movilizacion=17500;`,
      `INSERT INTO rrhh_trabajadores (         rut, nombres, apellido_paterno, apellido_materno, nacionalidad, fecha_nacimiento,          direccion, telefono, email, nivel_educacional, estado_civil,          afp_id, salud_id, cargas_familiares, banco, tipo_cuenta, numero_cuenta, entrega_riohs, es_representante_legal       ) VALUES (         '25910853-5', 'Amalia', 'Mera', 'Mora',          'COLOMBIANA', '1993-02-06',          'Adriana Zuanic 9501, casa 12', '+56 995267137', 'amaliameramora@outlook.es',          'MEDIA', 'SOLTERA',          (SELECT id FROM rrhh_afp WHERE nombre LIKE '%PLAN%' LIMIT 1),          (SELECT id FROM rrhh_salud WHERE nombre LIKE '%FONA%' LIMIT 1),          0, 'ESTADO', 'VISTA', '25910853',          0, 1       )       ON DUPLICATE KEY UPDATE          nombres=VALUES(nombres), apellido_paterno=VALUES(apellido_paterno), apellido_materno=VALUES(apellido_materno),         banco=VALUES(banco), tipo_cuenta=VALUES(tipo_cuenta), numero_cuenta=VALUES(numero_cuenta),         nacionalidad=VALUES(nacionalidad), nivel_educacional=VALUES(nivel_educacional);`,
      `INSERT IGNORE INTO rrhh_cargos (nombre) VALUES ('Bodeguero');`,
      `INSERT INTO rrhh_contratos (trabajador_id, cargo_id, sueldo_base, fecha_inicio, tipo_contrato, estado)         SELECT t.id, c.id, 400000, '2022-09-30', 'Indefinido', 'ACTIVO'         FROM rrhh_trabajadores t, rrhh_cargos c         WHERE t.rut = '25910853-5' AND c.nombre = 'Bodeguero'         ON DUPLICATE KEY UPDATE sueldo_base=400000, cargo_id=VALUES(cargo_id);`,
      `INSERT INTO rrhh_haberes_fijos (trabajador_id, colacion, movilizacion)         SELECT id, 22500, 22500 FROM rrhh_trabajadores WHERE rut = '25910853-5'         ON DUPLICATE KEY UPDATE colacion=22500, movilizacion=22500;`,
      `INSERT INTO rrhh_trabajadores (         rut, nombres, apellido_paterno, apellido_materno, nacionalidad, fecha_nacimiento,          direccion, telefono, email, nivel_educacional, estado_civil,          afp_id, salud_id, cargas_familiares, banco, tipo_cuenta, numero_cuenta, entrega_riohs, es_representante_legal       ) VALUES (         '11170135-', 'María Patricia', 'Jofré', 'Díaz',          'CHILENA', '1967-04-21',          'Ana María Ibazeta 7938', '+56 999462154', 'mariajofre1967@gmail.com',          'TECNICO', 'CASADA',          (SELECT id FROM rrhh_afp WHERE nombre LIKE '%ING %' LIMIT 1),          (SELECT id FROM rrhh_salud WHERE nombre LIKE '%FONA%' LIMIT 1),          0, 'ESTADO', 'VISTA', '11170135',          0, 1       )       ON DUPLICATE KEY UPDATE          nombres=VALUES(nombres), apellido_paterno=VALUES(apellido_paterno), apellido_materno=VALUES(apellido_materno),         banco=VALUES(banco), tipo_cuenta=VALUES(tipo_cuenta), numero_cuenta=VALUES(numero_cuenta),         nacionalidad=VALUES(nacionalidad), nivel_educacional=VALUES(nivel_educacional);`,
      `INSERT IGNORE INTO rrhh_cargos (nombre) VALUES ('Auxiliar Farmacéutico ');`,
      `INSERT INTO rrhh_contratos (trabajador_id, cargo_id, sueldo_base, fecha_inicio, tipo_contrato, estado)         SELECT t.id, c.id, 420000, '2022-10-31', 'Indefinido', 'ACTIVO'         FROM rrhh_trabajadores t, rrhh_cargos c         WHERE t.rut = '11170135-' AND c.nombre = 'Auxiliar Farmacéutico '         ON DUPLICATE KEY UPDATE sueldo_base=420000, cargo_id=VALUES(cargo_id);`,
      `INSERT INTO rrhh_haberes_fijos (trabajador_id, colacion, movilizacion)         SELECT id, 37500, 37500 FROM rrhh_trabajadores WHERE rut = '11170135-'         ON DUPLICATE KEY UPDATE colacion=37500, movilizacion=37500;`,
      `INSERT INTO rrhh_trabajadores (         rut, nombres, apellido_paterno, apellido_materno, nacionalidad, fecha_nacimiento,          direccion, telefono, email, nivel_educacional, estado_civil,          afp_id, salud_id, cargas_familiares, banco, tipo_cuenta, numero_cuenta, entrega_riohs, es_representante_legal       ) VALUES (         '18507025-5', 'Camila', 'Krstulovic', 'Marín',          'CHILENA', '1993-08-26',          'Del agua 9667, Villa las Palmas', '+56 934207363', 'camilakrstulovic@gmail.com',          'SUPERIOR', 'SOLTERA',          (SELECT id FROM rrhh_afp WHERE nombre LIKE '%MODE%' LIMIT 1),          (SELECT id FROM rrhh_salud WHERE nombre LIKE '%FONA%' LIMIT 1),          0, 'CHILE', 'CORRIENTE', '00-134-02296-03',          0, 1       )       ON DUPLICATE KEY UPDATE          nombres=VALUES(nombres), apellido_paterno=VALUES(apellido_paterno), apellido_materno=VALUES(apellido_materno),         banco=VALUES(banco), tipo_cuenta=VALUES(tipo_cuenta), numero_cuenta=VALUES(numero_cuenta),         nacionalidad=VALUES(nacionalidad), nivel_educacional=VALUES(nivel_educacional);`,
      `INSERT IGNORE INTO rrhh_cargos (nombre) VALUES ('Químico Farmacéutico ');`,
      `INSERT INTO rrhh_contratos (trabajador_id, cargo_id, sueldo_base, fecha_inicio, tipo_contrato, estado)         SELECT t.id, c.id, 1400000, '2022-12-05', 'Indefinido', 'ACTIVO'         FROM rrhh_trabajadores t, rrhh_cargos c         WHERE t.rut = '18507025-5' AND c.nombre = 'Químico Farmacéutico '         ON DUPLICATE KEY UPDATE sueldo_base=1400000, cargo_id=VALUES(cargo_id);`,
      `INSERT INTO rrhh_haberes_fijos (trabajador_id, colacion, movilizacion)         SELECT id, 75000, 75000 FROM rrhh_trabajadores WHERE rut = '18507025-5'         ON DUPLICATE KEY UPDATE colacion=75000, movilizacion=75000;`,
      `INSERT INTO rrhh_trabajadores (         rut, nombres, apellido_paterno, apellido_materno, nacionalidad, fecha_nacimiento,          direccion, telefono, email, nivel_educacional, estado_civil,          afp_id, salud_id, cargas_familiares, banco, tipo_cuenta, numero_cuenta, entrega_riohs, es_representante_legal       ) VALUES (         '24002416-', 'Magnolia', 'Castillo', 'Valdez',          'PERUANA', '1981-09-04',          'Guillermo Marconi 1230-C', '+56 972955051', 'castillomagnolia720@gmail.com',          'TECNICO', 'SOLTERA',          (SELECT id FROM rrhh_afp WHERE nombre LIKE '%MODE%' LIMIT 1),          (SELECT id FROM rrhh_salud WHERE nombre LIKE '%FONA%' LIMIT 1),          0, 'ESTADO', 'CORRIENTE', '2500233021',          0, 0       )       ON DUPLICATE KEY UPDATE          nombres=VALUES(nombres), apellido_paterno=VALUES(apellido_paterno), apellido_materno=VALUES(apellido_materno),         banco=VALUES(banco), tipo_cuenta=VALUES(tipo_cuenta), numero_cuenta=VALUES(numero_cuenta),         nacionalidad=VALUES(nacionalidad), nivel_educacional=VALUES(nivel_educacional);`,
      `INSERT IGNORE INTO rrhh_cargos (nombre) VALUES ('Auxiliar Farmacéutico ');`,
      `INSERT INTO rrhh_contratos (trabajador_id, cargo_id, sueldo_base, fecha_inicio, tipo_contrato, estado)         SELECT t.id, c.id, 700000, '2023-03-31', 'Indefinido', 'ACTIVO'         FROM rrhh_trabajadores t, rrhh_cargos c         WHERE t.rut = '24002416-' AND c.nombre = 'Auxiliar Farmacéutico '         ON DUPLICATE KEY UPDATE sueldo_base=700000, cargo_id=VALUES(cargo_id);`,
      `INSERT INTO rrhh_haberes_fijos (trabajador_id, colacion, movilizacion)         SELECT id, 20000, 20000 FROM rrhh_trabajadores WHERE rut = '24002416-'         ON DUPLICATE KEY UPDATE colacion=20000, movilizacion=20000;`,
      `INSERT INTO rrhh_trabajadores (         rut, nombres, apellido_paterno, apellido_materno, nacionalidad, fecha_nacimiento,          direccion, telefono, email, nivel_educacional, estado_civil,          afp_id, salud_id, cargas_familiares, banco, tipo_cuenta, numero_cuenta, entrega_riohs, es_representante_legal       ) VALUES (         '18510228-9', 'Andrés', 'Tapia', 'Sandoval',          'CHILENA', '1993-05-15',          'Llanquihue 3958', '+56 932783755', 'atapia.san@gmail.com',          'MEDIA', 'SOLTERO',          (SELECT id FROM rrhh_afp WHERE nombre LIKE '%MODE%' LIMIT 1),          (SELECT id FROM rrhh_salud WHERE nombre LIKE '%FONA%' LIMIT 1),          0, 'ESTADO', 'VISTA', '18510228',          0, 1       )       ON DUPLICATE KEY UPDATE          nombres=VALUES(nombres), apellido_paterno=VALUES(apellido_paterno), apellido_materno=VALUES(apellido_materno),         banco=VALUES(banco), tipo_cuenta=VALUES(tipo_cuenta), numero_cuenta=VALUES(numero_cuenta),         nacionalidad=VALUES(nacionalidad), nivel_educacional=VALUES(nivel_educacional);`,
      `INSERT IGNORE INTO rrhh_cargos (nombre) VALUES ('Bodeguero');`,
      `INSERT INTO rrhh_contratos (trabajador_id, cargo_id, sueldo_base, fecha_inicio, tipo_contrato, estado)         SELECT t.id, c.id, 450000, '2023-04-14', 'Indefinido', 'ACTIVO'         FROM rrhh_trabajadores t, rrhh_cargos c         WHERE t.rut = '18510228-9' AND c.nombre = 'Bodeguero'         ON DUPLICATE KEY UPDATE sueldo_base=450000, cargo_id=VALUES(cargo_id);`,
      `INSERT INTO rrhh_haberes_fijos (trabajador_id, colacion, movilizacion)         SELECT id, 22500, 22500 FROM rrhh_trabajadores WHERE rut = '18510228-9'         ON DUPLICATE KEY UPDATE colacion=22500, movilizacion=22500;`,
      `INSERT INTO rrhh_trabajadores (         rut, nombres, apellido_paterno, apellido_materno, nacionalidad, fecha_nacimiento,          direccion, telefono, email, nivel_educacional, estado_civil,          afp_id, salud_id, cargas_familiares, banco, tipo_cuenta, numero_cuenta, entrega_riohs, es_representante_legal       ) VALUES (         '15021347-9', 'Karina Isabel', 'Araos', 'Carrasco',          'CHILENA', '1981-10-25',          'Juan Ferra 7194', '+56 975299148', 'araoscarrasco@gmail.com',          'NIVEL SUPERIOR', 'SOLTERA',          (SELECT id FROM rrhh_afp WHERE nombre LIKE '%HABI%' LIMIT 1),          (SELECT id FROM rrhh_salud WHERE nombre LIKE '%FONA%' LIMIT 1),          0, 'ESTADO', 'VISTA', '15021347',          0, 1       )       ON DUPLICATE KEY UPDATE          nombres=VALUES(nombres), apellido_paterno=VALUES(apellido_paterno), apellido_materno=VALUES(apellido_materno),         banco=VALUES(banco), tipo_cuenta=VALUES(tipo_cuenta), numero_cuenta=VALUES(numero_cuenta),         nacionalidad=VALUES(nacionalidad), nivel_educacional=VALUES(nivel_educacional);`,
      `INSERT IGNORE INTO rrhh_cargos (nombre) VALUES ('Auxiliar Farmacéutico ');`,
      `INSERT INTO rrhh_contratos (trabajador_id, cargo_id, sueldo_base, fecha_inicio, tipo_contrato, estado)         SELECT t.id, c.id, 500000, '2023-06-18', 'Indefinido', 'ACTIVO'         FROM rrhh_trabajadores t, rrhh_cargos c         WHERE t.rut = '15021347-9' AND c.nombre = 'Auxiliar Farmacéutico '         ON DUPLICATE KEY UPDATE sueldo_base=500000, cargo_id=VALUES(cargo_id);`,
      `INSERT INTO rrhh_haberes_fijos (trabajador_id, colacion, movilizacion)         SELECT id, 35000, 35000 FROM rrhh_trabajadores WHERE rut = '15021347-9'         ON DUPLICATE KEY UPDATE colacion=35000, movilizacion=35000;`,
      `INSERT INTO rrhh_trabajadores (         rut, nombres, apellido_paterno, apellido_materno, nacionalidad, fecha_nacimiento,          direccion, telefono, email, nivel_educacional, estado_civil,          afp_id, salud_id, cargas_familiares, banco, tipo_cuenta, numero_cuenta, entrega_riohs, es_representante_legal       ) VALUES (         '19444575-K', 'Javiera', 'Matamoros', 'García',          'CHILENA', '1996-10-14',          'Pasaje El Volcán 9641', '+56 930731249', 'lt-sjaviera@hotmail.com',          'TECNICO', 'SOLTERA',          (SELECT id FROM rrhh_afp WHERE nombre LIKE '%PROV%' LIMIT 1),          (SELECT id FROM rrhh_salud WHERE nombre LIKE '%FONA%' LIMIT 1),          0, 'ESTADO', 'VISTA', '19444575',          0, 0       )       ON DUPLICATE KEY UPDATE          nombres=VALUES(nombres), apellido_paterno=VALUES(apellido_paterno), apellido_materno=VALUES(apellido_materno),         banco=VALUES(banco), tipo_cuenta=VALUES(tipo_cuenta), numero_cuenta=VALUES(numero_cuenta),         nacionalidad=VALUES(nacionalidad), nivel_educacional=VALUES(nivel_educacional);`,
      `INSERT INTO rrhh_trabajadores (         rut, nombres, apellido_paterno, apellido_materno, nacionalidad, fecha_nacimiento,          direccion, telefono, email, nivel_educacional, estado_civil,          afp_id, salud_id, cargas_familiares, banco, tipo_cuenta, numero_cuenta, entrega_riohs, es_representante_legal       ) VALUES (         'EXT-1-84', 'Yaneth', 'Chacalla', 'Anco',          'PERUANA', NULL,          '', '', '',          '', 'Soltero/a',          (SELECT id FROM rrhh_afp WHERE nombre LIKE '%%' LIMIT 1),          (SELECT id FROM rrhh_salud WHERE nombre LIKE '%%' LIMIT 1),          0, '', '', '',          0, 0       )       ON DUPLICATE KEY UPDATE          nombres=VALUES(nombres), apellido_paterno=VALUES(apellido_paterno), apellido_materno=VALUES(apellido_materno),         banco=VALUES(banco), tipo_cuenta=VALUES(tipo_cuenta), numero_cuenta=VALUES(numero_cuenta),         nacionalidad=VALUES(nacionalidad), nivel_educacional=VALUES(nivel_educacional);`,
      `INSERT INTO rrhh_trabajadores (         rut, nombres, apellido_paterno, apellido_materno, nacionalidad, fecha_nacimiento,          direccion, telefono, email, nivel_educacional, estado_civil,          afp_id, salud_id, cargas_familiares, banco, tipo_cuenta, numero_cuenta, entrega_riohs, es_representante_legal       ) VALUES (         'EXT-2-252', 'Sonia', 'Condori', 'Arena',          'BOLIVIANA', NULL,          '', '', '',          '', 'Soltero/a',          (SELECT id FROM rrhh_afp WHERE nombre LIKE '%%' LIMIT 1),          (SELECT id FROM rrhh_salud WHERE nombre LIKE '%%' LIMIT 1),          0, '', '', '',          0, 0       )       ON DUPLICATE KEY UPDATE          nombres=VALUES(nombres), apellido_paterno=VALUES(apellido_paterno), apellido_materno=VALUES(apellido_materno),         banco=VALUES(banco), tipo_cuenta=VALUES(tipo_cuenta), numero_cuenta=VALUES(numero_cuenta),         nacionalidad=VALUES(nacionalidad), nivel_educacional=VALUES(nivel_educacional);`,
      `INSERT INTO rrhh_trabajadores (         rut, nombres, apellido_paterno, apellido_materno, nacionalidad, fecha_nacimiento,          direccion, telefono, email, nivel_educacional, estado_civil,          afp_id, salud_id, cargas_familiares, banco, tipo_cuenta, numero_cuenta, entrega_riohs, es_representante_legal       ) VALUES (         'EXT-3-287', 'Adriana', 'Bravo', 'Valles',          'VENEZOLANA', NULL,          '', '', '',          '', 'Soltero/a',          (SELECT id FROM rrhh_afp WHERE nombre LIKE '%%' LIMIT 1),          (SELECT id FROM rrhh_salud WHERE nombre LIKE '%%' LIMIT 1),          0, '', '', '',          0, 0       )       ON DUPLICATE KEY UPDATE          nombres=VALUES(nombres), apellido_paterno=VALUES(apellido_paterno), apellido_materno=VALUES(apellido_materno),         banco=VALUES(banco), tipo_cuenta=VALUES(tipo_cuenta), numero_cuenta=VALUES(numero_cuenta),         nacionalidad=VALUES(nacionalidad), nivel_educacional=VALUES(nivel_educacional);`,
      `INSERT INTO rrhh_trabajadores (         rut, nombres, apellido_paterno, apellido_materno, nacionalidad, fecha_nacimiento,          direccion, telefono, email, nivel_educacional, estado_civil,          afp_id, salud_id, cargas_familiares, banco, tipo_cuenta, numero_cuenta, entrega_riohs, es_representante_legal       ) VALUES (         'EXT-4-790', 'Estefania', 'Huayraña', 'Espinoza',          'CHILENA', NULL,          '', '', '',          '', 'Soltero/a',          (SELECT id FROM rrhh_afp WHERE nombre LIKE '%%' LIMIT 1),          (SELECT id FROM rrhh_salud WHERE nombre LIKE '%%' LIMIT 1),          0, '', '', '',          0, 0       )       ON DUPLICATE KEY UPDATE          nombres=VALUES(nombres), apellido_paterno=VALUES(apellido_paterno), apellido_materno=VALUES(apellido_materno),         banco=VALUES(banco), tipo_cuenta=VALUES(tipo_cuenta), numero_cuenta=VALUES(numero_cuenta),         nacionalidad=VALUES(nacionalidad), nivel_educacional=VALUES(nivel_educacional);`,
      `INSERT INTO rrhh_trabajadores (         rut, nombres, apellido_paterno, apellido_materno, nacionalidad, fecha_nacimiento,          direccion, telefono, email, nivel_educacional, estado_civil,          afp_id, salud_id, cargas_familiares, banco, tipo_cuenta, numero_cuenta, entrega_riohs, es_representante_legal       ) VALUES (         'EXT-5-473', 'Daniela', 'Soto', 'Zapata',          'CHILENA', NULL,          '', '', '',          '', 'Soltero/a',          (SELECT id FROM rrhh_afp WHERE nombre LIKE '%%' LIMIT 1),          (SELECT id FROM rrhh_salud WHERE nombre LIKE '%%' LIMIT 1),          0, '', '', '',          0, 0       )       ON DUPLICATE KEY UPDATE          nombres=VALUES(nombres), apellido_paterno=VALUES(apellido_paterno), apellido_materno=VALUES(apellido_materno),         banco=VALUES(banco), tipo_cuenta=VALUES(tipo_cuenta), numero_cuenta=VALUES(numero_cuenta),         nacionalidad=VALUES(nacionalidad), nivel_educacional=VALUES(nivel_educacional);`,
      `INSERT INTO rrhh_trabajadores (         rut, nombres, apellido_paterno, apellido_materno, nacionalidad, fecha_nacimiento,          direccion, telefono, email, nivel_educacional, estado_civil,          afp_id, salud_id, cargas_familiares, banco, tipo_cuenta, numero_cuenta, entrega_riohs, es_representante_legal       ) VALUES (         'EXT-6-367', 'Hilda', 'Hidalgo', 'Hidalgo',          'CHILENA', NULL,          '', '', '',          '', 'Soltero/a',          (SELECT id FROM rrhh_afp WHERE nombre LIKE '%%' LIMIT 1),          (SELECT id FROM rrhh_salud WHERE nombre LIKE '%%' LIMIT 1),          0, '', '', '',          0, 0       )       ON DUPLICATE KEY UPDATE          nombres=VALUES(nombres), apellido_paterno=VALUES(apellido_paterno), apellido_materno=VALUES(apellido_materno),         banco=VALUES(banco), tipo_cuenta=VALUES(tipo_cuenta), numero_cuenta=VALUES(numero_cuenta),         nacionalidad=VALUES(nacionalidad), nivel_educacional=VALUES(nivel_educacional);`,
      `INSERT INTO rrhh_trabajadores (         rut, nombres, apellido_paterno, apellido_materno, nacionalidad, fecha_nacimiento,          direccion, telefono, email, nivel_educacional, estado_civil,          afp_id, salud_id, cargas_familiares, banco, tipo_cuenta, numero_cuenta, entrega_riohs, es_representante_legal       ) VALUES (         'EXT-7-206', 'Alder', 'Gamero', 'Hernández',          'COLOMBIANA', '1980-09-27',          '', '', '',          '', 'Soltero/a',          (SELECT id FROM rrhh_afp WHERE nombre LIKE '%%' LIMIT 1),          (SELECT id FROM rrhh_salud WHERE nombre LIKE '%%' LIMIT 1),          0, '', '', '',          0, 0       )       ON DUPLICATE KEY UPDATE          nombres=VALUES(nombres), apellido_paterno=VALUES(apellido_paterno), apellido_materno=VALUES(apellido_materno),         banco=VALUES(banco), tipo_cuenta=VALUES(tipo_cuenta), numero_cuenta=VALUES(numero_cuenta),         nacionalidad=VALUES(nacionalidad), nivel_educacional=VALUES(nivel_educacional);`,
      `INSERT INTO rrhh_trabajadores (         rut, nombres, apellido_paterno, apellido_materno, nacionalidad, fecha_nacimiento,          direccion, telefono, email, nivel_educacional, estado_civil,          afp_id, salud_id, cargas_familiares, banco, tipo_cuenta, numero_cuenta, entrega_riohs, es_representante_legal       ) VALUES (         'EXT-8-431', 'Cinthya', 'Ochochoque', 'Fernández',          'CHILENA', NULL,          '', '', '',          '', 'Soltero/a',          (SELECT id FROM rrhh_afp WHERE nombre LIKE '%%' LIMIT 1),          (SELECT id FROM rrhh_salud WHERE nombre LIKE '%%' LIMIT 1),          0, '', '', '',          0, 0       )       ON DUPLICATE KEY UPDATE          nombres=VALUES(nombres), apellido_paterno=VALUES(apellido_paterno), apellido_materno=VALUES(apellido_materno),         banco=VALUES(banco), tipo_cuenta=VALUES(tipo_cuenta), numero_cuenta=VALUES(numero_cuenta),         nacionalidad=VALUES(nacionalidad), nivel_educacional=VALUES(nivel_educacional);`,
      `INSERT INTO rrhh_trabajadores (         rut, nombres, apellido_paterno, apellido_materno, nacionalidad, fecha_nacimiento,          direccion, telefono, email, nivel_educacional, estado_civil,          afp_id, salud_id, cargas_familiares, banco, tipo_cuenta, numero_cuenta, entrega_riohs, es_representante_legal       ) VALUES (         'EXT-9-656', 'María Eugenia', 'Ayala', 'Arauz',          'CHILENA', NULL,          '', '', '',          '', 'Soltero/a',          (SELECT id FROM rrhh_afp WHERE nombre LIKE '%%' LIMIT 1),          (SELECT id FROM rrhh_salud WHERE nombre LIKE '%%' LIMIT 1),          0, '', '', '',          0, 0       )       ON DUPLICATE KEY UPDATE          nombres=VALUES(nombres), apellido_paterno=VALUES(apellido_paterno), apellido_materno=VALUES(apellido_materno),         banco=VALUES(banco), tipo_cuenta=VALUES(tipo_cuenta), numero_cuenta=VALUES(numero_cuenta),         nacionalidad=VALUES(nacionalidad), nivel_educacional=VALUES(nivel_educacional);`,
      `INSERT INTO rrhh_trabajadores (         rut, nombres, apellido_paterno, apellido_materno, nacionalidad, fecha_nacimiento,          direccion, telefono, email, nivel_educacional, estado_civil,          afp_id, salud_id, cargas_familiares, banco, tipo_cuenta, numero_cuenta, entrega_riohs, es_representante_legal       ) VALUES (         'EXT-10-922', 'Estephanie', 'Ardiles', 'Ramírez',          'CHILENA', NULL,          '', '', '',          '', 'Soltero/a',          (SELECT id FROM rrhh_afp WHERE nombre LIKE '%%' LIMIT 1),          (SELECT id FROM rrhh_salud WHERE nombre LIKE '%%' LIMIT 1),          0, '', '', '',          0, 0       )       ON DUPLICATE KEY UPDATE          nombres=VALUES(nombres), apellido_paterno=VALUES(apellido_paterno), apellido_materno=VALUES(apellido_materno),         banco=VALUES(banco), tipo_cuenta=VALUES(tipo_cuenta), numero_cuenta=VALUES(numero_cuenta),         nacionalidad=VALUES(nacionalidad), nivel_educacional=VALUES(nivel_educacional);`,
      `INSERT INTO rrhh_trabajadores (         rut, nombres, apellido_paterno, apellido_materno, nacionalidad, fecha_nacimiento,          direccion, telefono, email, nivel_educacional, estado_civil,          afp_id, salud_id, cargas_familiares, banco, tipo_cuenta, numero_cuenta, entrega_riohs, es_representante_legal       ) VALUES (         'EXT-11-580', 'Cristobal Matías', 'León', 'Bustamante',          'CHILENA', NULL,          '', '', '',          '', 'Soltero/a',          (SELECT id FROM rrhh_afp WHERE nombre LIKE '%%' LIMIT 1),          (SELECT id FROM rrhh_salud WHERE nombre LIKE '%%' LIMIT 1),          0, '', '', '',          0, 0       )       ON DUPLICATE KEY UPDATE          nombres=VALUES(nombres), apellido_paterno=VALUES(apellido_paterno), apellido_materno=VALUES(apellido_materno),         banco=VALUES(banco), tipo_cuenta=VALUES(tipo_cuenta), numero_cuenta=VALUES(numero_cuenta),         nacionalidad=VALUES(nacionalidad), nivel_educacional=VALUES(nivel_educacional);`
    ];

    let count = 0;
    for (const q of queries) {
      if(q.trim() !== '') {
        await connection.query(q);
        count++;
      }
    }

    return NextResponse.json({ success: true, message: `${count} instrucciones SQL ejecutadas para importar datos.` });
  } catch (error: any) {
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  } finally {
    connection.release();
  }
}